[package]
org = "sithi"
name = "booking_api"
version = "0.1.0"
distribution = "2201.12.7"

[build-options]
observabilityIncluded = true

[[platform.java11.dependency]]
groupId = "com.mysql"
artifactId = "mysql-connector-j"
version = "8.2.0"

